### ISSUE TITLE
Add an option to skip camel casing keys

### ISSUE THREAD

**Issue by adamgruber** [adamgruber/sass-extract-js#3]
The default behavior of this plugin is to camelCase variable keys during the transform.
```sass
$my-variable-name: 10px //=> myVariableName: '10px'
```

This may be undesirable for some so an option to skip this part of the transform would be a good idea.

**Comment by adamgruber** [comment]
v0.2.0 introduces options support including a `camelCase` option. Setting this to `false` will skip the camel case transformation.

**Comment by Coord** [comment]
It looks like this option is not working with nested objects.

**Comment by adamgruber** [comment]
@Coord Mind opening a separate issue with some more details and code to reproduce?
