### ISSUE TITLE
DeprecationWarning: Module Chunks

### ISSUE THREAD

**Issue by dgonzalezr** [adamgruber/sass-extract-js#6]
I'm getting the following warning/error when parsing a bootstrap _variable.scss file. My setup is it's based on [next.js](https://github.com/zeit/next.js)

```
 ERROR  Failed to compile with 5 errors

This dependency was not found:

* fs in ./node_modules/mkdirp/index.js, ./node_modules/node-sass/lib/extensions.js and 3 others

To install it, you can run: npm install --save fs
(node:9903) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead
```

I'm not really whether if is related to this specific module or the [sass-extract](sass-extract) module, so I raised the same [issue](https://github.com/jgranstrom/sass-extract/issues/28) there.

**Comment by JoaoTMDias** [comment]
same here. Any news regarding this?

**Comment by adamgruber** [comment]
I did some digging on this tonight. I believe the problem comes from importing `sass-extract` since it is not meant to be run in the browser. (It relies on node-sass which relies on fs which doesn't exist in the browser.)

The correct way to make it work (assuming you are also using webpack) is to use [sass-extract-loader](https://github.com/jgranstrom/sass-extract-loader). Here's an example:
```js
import React, { Component } from 'react';
import { ThemeProvider } from 'styled-components';
import logo from './logo.svg';
import './App.css';

const theme = require('sass-extract-loader?{"plugins": ["sass-extract-js"]}!./vars.scss');

class App extends Component {
  render() {
    return (
      <ThemeProvider theme={theme}>
        <div className="App">
          <header className="App-header">
            <img src={logo} className="App-logo" alt="logo" />
            <h1 className="App-title">Welcome to React</h1>
          </header>
          <p className="App-intro">
            To get started, edit <code>src/App.js</code> and save to reload.
          </p>
        </div>
      </ThemeProvider>
    );
  }
}

export default App;
```

I'll have to update the documentation to reflect this.

**Comment by dgonzalezr** [comment]
Thanks @adamgruber 🙂. I just checked and your suggestion works really good with [Next.js](https://github.com/zeit/next.js). If anyone is interested about it here's a basic [starter kit repo](https://github.com/dgonzalezr/nextjs-react-starter-kit) combining bootstrap scss variables with [styled-components](https://www.styled-components.com/).

**Comment by JoaoTMDias** [comment]
@adamgruber Thank you for your quick response!

@dgonzalezr Where is the beginning of the path to the variables file? from the project root directory? Or from the file where that instruction is being written?

Any way, i got this:
This dependency was not found:

* sass-extract-loader?{
    "plugins": ["sass-extract-js"]
}!./src/assets/styles/global/_settings.scss in ./src/layouts/index.jsx

To install it, you can run: npm install --save sass-extract-loader?{
    "plugins": ["sass-extract-js"]
}!./src/assets/styles/global/_settings.scss

(I'm using gatsbyjs not next.js, but I would assume the process would be similar)

**Comment by dgonzalezr** [comment]
@JoaoTMDias you can see my setup in this [repo](https://github.com/dgonzalezr/nextjs-react-starter-kit).

I'm using [Next.js](https://github.com/zeit/next.js). I'd put the code in an `index.tsx` file which wrap my entire app and is a level up from where my `/scss` folder is.

```sh
└── pages
    └── index.tsx
└── src
    └── app
    └── scss
        └── bootstrap
            └── _variables.scss
        └── _default.scss
        └── main.scss
```

So, I have the following:

```js
const theme = require(`sass-extract-loader?{
    "plugins": ["sass-extract-js"]
}!../src/scss/bootstrap/` + '_variables.scss');
```

Hope it helps you 🙂

**Comment by adamgruber** [comment]
@JoaoTMDias Did you make sure to npm install sass-extract-loader?

**Comment by dgonzalezr** [comment]
@adamgruber I think it is something related with the path to the *.scss file. I got the same until I finally set it correctly 😉

**Comment by emsiuser1** [comment]
What if you aren't using webpack? I am using a gulp compiling process. Is there anyway to use this library with that?
