### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by penx** [adamgruber/sass-extract-js#8]
Would be useful to have a CLI as follows:

```
sass-extract-js ./path/to/scss ./path/to/output
```

Or perhaps a separate project that provided the CLI.

**Comment by adamgruber** [comment]
Since this project is just a plugin, I think it would make more sense for [sass-extract](https://github.com/jgranstrom/sass-extract) to provide the CLI with support for any available plugins. I suggest opening an issue there.
